apiVersion: v2
name: prometheus
description: Kube Prometheus Stack
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 72.6.2
    repository: https://prometheus-community.github.io/helm-charts
